name: Rohit Sanbhadti's Blog
description: Rohit's home for anything and everything.
url: http://rohits47.com
markdown: kramdown
#markdown: rdiscount
permalink: pretty
#pygments: true
exclude: ['README.md']
baseurl: /
